Repository youcan-shop/cod-theme, pull requests merged in 2023-05, with the labels that each got.

#341 remove icons from settings
  sections/desktop-slider.liquid
  sections/featured-product-slider.liquid
Labels: 💻 Ready for review

#340 DARK : fix console log errors for COD v1
  assets/cart.js
  sections/main-collection.liquid
  snippets/general-review.liquid
  snippets/head-config.liquid
  snippets/reviews.liquid
Labels: 💻 Ready for review

#344 SHOP2-474: COD v1 - Update `averageRating` to product template and product section
  assets/reviews-count.js
  sections/product-reviews.liquid
  sections/product.liquid
  snippets/head-config.liquid
  snippets/product-home.liquid
  snippets/reviews.liquid
Labels: 🪄 Enhancement, 💻 Ready for review

#345 YSHOP2-500 : COD V1 > Countdown functionality triggering an infinite loop making the web page crush
  assets/helper.js
Labels: ✅ Reviewed

#347 YSHOP2-505 : Search page > fix UI bugs
  assets/cart.js
  assets/main.css
  assets/main.js
  assets/queries-handler.js
  locales/ar.default.json
  sections/main-cart.liquid
  sections/main-search.liquid
  styles/main.scss
Labels: 💻 Ready for review

#348 YSHOP2-559 : COD V1 > Some sections doesn't have unique CSS class
  assets/main.js
  assets/video.js
  sections/desktop-slider.liquid
  sections/feature-products-by-category.liquid
  sections/featured-collections.liquid
  sections/featured-product-slider.liquid
  sections/featured-products.liquid
  sections/main-video.liquid
  templates/index.json
Labels: 💻 Ready for review

#352 YSHOP2-595 : COD v1 > Default text colors for themes
  sections/featured-products.liquid
  sections/multi-column.liquid
  templates/index.json
Labels: ✅ Reviewed
