Repository youcan-shop/cod-theme, pull requests merged in 2023-04, with the labels that each got.

#266 YSHOP2-253: Removing the countdown settings from the List of Products section
  sections/feature-products-by-category.liquid
  sections/featured-products.liquid
Labels: ready for review

#269 YSHOP2-294: [Navbar] Setting "Cart badge color" not used
  .github/pull_request_template.md
  assets/navbar.css
  styles/navbar.scss
Labels: ready for review

#270 fix: money filter bug on product column
  snippets/product-home.liquid
Labels: bug

#274 YSHOP2-316: Products List > Wrong position of the banner when set in the bottom
  snippets/product-preview.liquid
Labels: ready for review

#276 YSHOP2-291: Theme 1 > Products slider: Changing the background color is not applied to the background
  sections/featured-product-slider.liquid
Labels: ready for review

#278 YSHOP2-291: The background color should extend full width in mobile
  sections/featured-product-slider.liquid
Labels: ready for review

#279 YSHOP2-312: Products Slider > The text color is not applied properly
  sections/featured-product-slider.liquid
  templates/index.json
Labels: ready for review

#280 YSHOP2-295: [Navbar] Links font weight doesn't seems to be used
  assets/navbar.css
  styles/navbar.scss
Labels: ready for review

#281 YSHOP2-295: Import navbar font
  sections/main-navbar.liquid
Labels: ready for review

#283 YSHOP2-321: Single Product > On mobile, the product image and the variants take half of the screen each
  assets/product.css
  styles/product.scss
Labels: ready for review

#284 YSHOP2-326 : COD v1 [Product column] Padding not working
  sections/product-column.liquid
  sections/product.liquid
Labels: ready for review

#285 YSHOP2-315: Products Slider > Banner settings are not functioning
  sections/featured-product-slider.liquid
  snippets/product-slider.liquid
Labels: ready for review

#290 YSHOP2-313: Products Slider > Only one product is displayed when the transition type is Fade
  sections/featured-product-slider.liquid
Labels: ready for review

#288 YSHOP2-328: [Feature products by category] Padding top seems to have extra padding that the one configured
  sections/feature-products-by-category.liquid
Labels: ready for review

#287 YSHOP2-329: [Features collections] Padding bottom does not seems to work
  assets/featured-collections.css
  sections/featured-collections.liquid
  styles/featured-collections.scss
Labels: ready for review

#291 YSHOP2-335 : COD v1 Express checkout bloc - Gap between input fields settings not working
  assets/express-checkout.css
  sections/product.liquid
  snippets/express-checkout.liquid
  snippets/single-product.liquid
  styles/express-checkout.scss
  styles/main.scss
  templates/index.json
Labels: ready for review

#292 YSHOP2-310 : COD v1 > [Footer] Dissociate the social media from the mentions
  assets/footer.css
  assets/main.css
  sections/main-footer.liquid
  styles/footer.scss
  styles/main.scss
Labels: ready for review

#294 DARK : COD V1 > Product column section > fix compare price value error
  snippets/product-home.liquid
Labels: ready for review

#298 DARK : COD v1 > fix the visibility of reviews in Product & home pages
  assets/reviews-count.js
  assets/reviews.js
  sections/product-reviews.liquid
  sections/product.liquid
  snippets/product-home.liquid
  snippets/reviews.liquid
Labels: ready for review

#299 YSHOP2-354 : Single product > Add to card size is small
  assets/main.css
  sections/product.liquid
  snippets/add-to-cart.liquid
  styles/main.scss
Labels: ready for review

#300 YSHOP2-356 : Single product > Stock > set default limit value
  assets/stock.css
  sections/product.liquid
  snippets/single-product.liquid
  snippets/stock.liquid
  styles/stock.scss
Labels: ready for review

#297 YSHOP2-350: Video > The video section should have bottom and top padding settings
  assets/product-column.css
  sections/main-video.liquid
  styles/product-column.scss
  templates/index.json
Labels: ready for review

#302 YSHOP2-324: As a seller, I want to be able to add an Upsell page
  assets/upsell.css
  assets/upsell.js
  assets/youcan-js.min.js
  locales/ar.default.json
  locales/en.json
  locales/fr.json
  sections/main-upsell.liquid
  styles/upsell.scss
  templates/upsell.json
Labels: ready for review

#303 DARK: update theme settings
  config/settings_data.json
Labels: enhancement, ready for review

#304 DARK: fix video container
  sections/main-video.liquid
Labels: enhancement

#305 DARK: single product ratings
  assets/reviews-count.js
  snippets/general-review.liquid
Labels: requested changes

#309 YSHOP2-387: Cart drawer doesn’t have currency
  assets/add-to-cart.js
  assets/cart-drawer.css
  styles/cart-drawer.scss
Labels: ready for review

#315 update index.json settings
  templates/index.json
Labels: 💻 Ready for review

#310 YSHOP2-375: Wording update for section/blocks settings
  sections/feature-products-by-category.liquid
  templates/index.json
Labels: ✅ Reviewed

#313 YSHOP2-377: Section initial background/text color is not getting applied
  sections/feature-products-by-category.liquid
  templates/index.json
Labels: 🐞 Bug, 💻 Ready for review

#316 chore(package): Update CLI dev command
  package.json
Labels: 🪄 Enhancement, ✅ Reviewed

#318 Theme QA > add dedicated setting for title text color
  sections/feature-products-by-category.liquid
Labels: 🪄 Enhancement

#311 Theme QA > Remove background image setting
  sections/feature-products-by-category.liquid
Labels: ✅ Reviewed

#322 Multi-column block description should accept text not html
  sections/multi-column.liquid
Labels: 🐞 Bug, ✅ Reviewed

#319 YSHOP2-385: Add toggle setting to hide the footer section
  sections/main-footer.liquid
Labels: 💻 Ready for review

#321 YSHOP2-396 : Multi-column Buttons to be removed
  sections/multi-column.liquid
Labels: 💻 Ready for review

#323 YSHOP2-388 : Navbar global setting to be removed
  config/settings_schema.json
Labels: 💻 Ready for review

#324 YSHOP2-398: Fix default Columns count
  sections/multi-column.liquid
Labels: 💻 Ready for review

#326 YSHOP2-389 : Naming conventions, first letter uppercase only (Part 1)
  config/settings_schema.json
  sections/desktop-slider.liquid
  sections/featured-product-slider.liquid
  sections/featured-products.liquid
  sections/multi-column.liquid
  sections/product-column.liquid
Labels: 💻 Ready for review

#325 Theme QA > Fix Notice bar
  assets/notice-bar.css
  sections/notice-bar.liquid
  styles/notice-bar.scss
Labels: ✅ Reviewed

#327 YSHOP2-403: Express checkout button
  snippets/single-product.liquid
Labels: 💻 Ready for review

#328 YSHOP2-404: Stock, description, countdown to be limited to 1
  sections/product.liquid
Labels: 💻 Ready for review

#331 YSHOP2-410: "Show navbar shadow” is not working
  sections/main-navbar.liquid
  snippets/head-config.liquid
Labels: 🪄 Enhancement, 💻 Ready for review

#332 YSHOP2-409: update the settings naming
  config/settings_schema.json
Labels: 🪄 Enhancement, ✅ Reviewed

#329 YSHOP2-407: Option to hide the nav-bar
  config/settings_data.json
  sections/main-footer.liquid
  sections/main-navbar.liquid
Labels: ✅ Reviewed

#330 YSHOP2-389 : Naming conventions, first letter uppercase only (part 2)
  sections/feature-products-by-category.liquid
  sections/featured-collections.liquid
  sections/featured-product-slider.liquid
  sections/featured-products.liquid
  sections/main-express-checkout.liquid
  sections/main-navbar.liquid
  sections/main-video.liquid
  sections/multi-column.liquid
  sections/notice-bar.liquid
  sections/product-column.liquid
  sections/product.liquid
Labels: ✅ Reviewed

#335 YSHOP2-416: For loading optimization load the video thumbnail first before you load the video
  assets/video.css
  assets/video.js
  assets/video_default_image.jpg
  sections/main-video.liquid
  styles/video.scss
  templates/index.json
Labels: 🪄 Enhancement, ✅ Reviewed

#336 YSHOP2-414: Enlarging Mobile & Desktop Settings text
  sections/desktop-slider.liquid
  sections/featured-product-slider.liquid
Labels: 💻 Ready for review

#338 YSHOP2-325 : Products Slider > Display countdown even if time runs out
  assets/helper.js
Labels: ✅ Reviewed

#339 update COD Theme settings
  assets/collection-listing.css
  assets/navbar.css
  assets/product-column.css
  assets/product-listing.css
  sections/main-navbar.liquid
  sections/product.liquid
  snippets/head-config.liquid
  snippets/product-images-showcase.liquid
  snippets/single-product.liquid
  styles/collection-listing.scss
  styles/navbar.scss
  styles/product-column.scss
  styles/product-listing.scss
  templates/index.json
Labels: 💻 Ready for review
